title: Giorgio Melloni
description: code.projects.bioinfo.blog
show_downloads: false
google_analytics: UA-102057877-1
markdown: kramdown

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - README.md
  - projects.md

email: melloni.giorgio@gmail.com
github_username: gmelloni
