title: Giorgio Melloni
author: Giorgio Melloni
description: code.projects.bioinfo.blog
show_downloads: false
google_analytics: UA-102057877-1

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - projects.md
  - publications.md
  - about.md

email: melloni.giorgio@gmail.com
github_username: gmelloni
